name: FastAPI Cloud Build

on:
  push:
    branches: ["fastapicloud/*"]
  pull_request:
    branches: ["fastapicloud/*"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"

      - name: Build
        run: |
          while read -r gomod_dir; do
            pushd "$gomod_dir" > /dev/null
            tags="$(go run knative.dev/toolbox/go-ls-tags@latest --joiner=,)"
            echo "Building ${gomod_dir} with tags: ${tags}"
            go test -vet=off -tags "${tags}" -exec echo ./... || failed=$?
            popd > /dev/null
            if (( failed )); then
              echo "Build failed in module $gomod_dir" >&2
              exit $failed
            fi
          done < <(go run knative.dev/toolbox/modscope@latest list --path)
